import type { Metadata } from "next";
import { Open_Sans, Syne } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import "@fortawesome/fontawesome-free/css/all.min.css";
import NavBar from "@/components/(global)/NavBar";
import "keen-slider/keen-slider.min.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

const open = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open",
  weight : 'variable'
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  weight : 'variable'

});

export const metadata: Metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background  antialiased ",
            syne.className
          )}
        >
          <NavBar className="fixed right-0 left-0" />
          <main>
            {children}
            <SpeedInsights />
          </main>
          <NavBar className=" bg-black border-black" />
        </body>
      </html>
    </>
  );
}
