import type { Metadata } from "next";
import { Open_Sans , Syne} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import '@fortawesome/fontawesome-free/css/all.min.css'
import NavBar from "@/components/(global)/NavBar";
import 'keen-slider/keen-slider.min.css'

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const syne = Syne({
  subsets: ['latin'],
  variable: '--font-syne',
})



export const metadata: Metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          syne.className
        )}
      >
        <NavBar className="fixed right-0 left-0"/>
        <main className={`${syne.className }  ${open_sans.className}`}>{children}</main>
        <NavBar className=" bg-black border-black"/>
      </body>
    </html>
  );
}
